package entity

import "errors"

var (
	ErrInvalidInput            = errors.New("invalid input")
	ErrEmailAlreadyExists      = errors.New("email already exists")
	ErrInvalidCredentials      = errors.New("invalid credentials")
	ErrUserNotFound            = errors.New("user not found")
	ErrUserSuspended           = errors.New("user suspended")
	ErrRefreshTokenMissing     = errors.New("refresh token missing")
	ErrRefreshTokenInvalid     = errors.New("refresh token invalid")
	ErrRefreshTokenExpired     = errors.New("refresh token expired")
	ErrRefreshTokenRevoked     = errors.New("refresh token revoked")
	ErrRefreshTokenReused      = errors.New("refresh token reused")
	ErrUnauthorized            = errors.New("unauthorized")
	ErrCSRFInvalid             = errors.New("csrf token invalid")
	ErrRateLimitExceeded       = errors.New("rate limit exceeded")
	ErrAdminRequired           = errors.New("admin required")
	ErrUserManagementForbidden = errors.New("user management forbidden")
	ErrUserStatusConflict      = errors.New("user status conflict")

	ErrVideoNotFound         = errors.New("video not found")
	ErrVideoForbidden        = errors.New("video forbidden")
	ErrVideoStateConflict    = errors.New("video state conflict")
	ErrVideoNotPublic        = errors.New("video not public")
	ErrUploadExpired         = errors.New("upload expired")
	ErrObjectNotFound        = errors.New("object not found")
	ErrIdempotencyConflict   = errors.New("idempotency conflict")
	ErrVideoSourceInvalid    = errors.New("video source invalid")
	ErrVideoOutputInvalid    = errors.New("video output invalid")
	ErrProcessingJobNotFound = errors.New("processing job not found")
	ErrProcessingJobConflict = errors.New("processing job conflict")
	ErrCleanupJobNotFound    = errors.New("cleanup job not found")
	ErrCleanupJobConflict    = errors.New("cleanup job conflict")
	ErrStorageUnavailable    = errors.New("storage unavailable")
	ErrMediaProcessingFailed = errors.New("media processing failed")
	ErrCursorInvalid         = errors.New("cursor invalid")
)
